/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.98.0
  Forc version: 0.66.6
  Fuel-Core version: 0.40.4
*/

import { Contract, Interface } from "fuels";
import type {
  Provider,
  Account,
  StorageSlot,
  Address,
  BigNumberish,
  BN,
  Bytes,
  FunctionFragment,
  InvokeFunction,
  StrSlice,
} from 'fuels';

import type { Enum } from "./common";

export enum UnsafeParamsInput { ZeroAddressRedeemer = 'ZeroAddressRedeemer', ZeroTimelock = 'ZeroTimelock', ZeroAmount = 'ZeroAmount' };
export enum UnsafeParamsOutput { ZeroAddressRedeemer = 'ZeroAddressRedeemer', ZeroTimelock = 'ZeroTimelock', ZeroAmount = 'ZeroAmount' };
export enum UnsafeTransferInput { InvalidAsset = 'InvalidAsset', InvalidAmount = 'InvalidAmount' };
export enum UnsafeTransferOutput { InvalidAsset = 'InvalidAsset', InvalidAmount = 'InvalidAmount' };

export type AddressInput = { bits: string };
export type AddressOutput = AddressInput;
export type AssetIdInput = { bits: string };
export type AssetIdOutput = AssetIdInput;
export type InitiatedEventInput = { order_ID: string, secret_hash: string, amount: BigNumberish };
export type InitiatedEventOutput = { order_ID: string, secret_hash: string, amount: BN };
export type RedeemedEventInput = { order_ID: string, secret_hash: string, secret: Bytes };
export type RedeemedEventOutput = RedeemedEventInput;
export type RefundedEventInput = { order_ID: string };
export type RefundedEventOutput = RefundedEventInput;

export type HTLCFuelConfigurables = Partial<{
  token: AssetIdInput;
}>;

const abi = {
  "programType": "contract",
  "specVersion": "1",
  "encodingVersion": "1",
  "concreteTypes": [
    {
      "type": "()",
      "concreteTypeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
    },
    {
      "type": "b256",
      "concreteTypeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
    },
    {
      "type": "bool",
      "concreteTypeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
    },
    {
      "type": "enum UnsafeParams",
      "concreteTypeId": "6a0e812c60ce32272fec27674115bfb9f4ad3a91d73b6fbb5e0ae33b60a13a22",
      "metadataTypeId": 0
    },
    {
      "type": "enum UnsafeTransfer",
      "concreteTypeId": "f1e0d6f9f415271a3b3f021e940e5c3b24ba3c3bab4a7d7e35ff36362823392d",
      "metadataTypeId": 1
    },
    {
      "type": "str",
      "concreteTypeId": "8c25cb3686462e9a86d2883c5688a22fe738b0bbc85f458d2d2b5f3f667c6d5a"
    },
    {
      "type": "struct InitiatedEvent",
      "concreteTypeId": "8d3f5112b0625606638ebdeb0911afb338b7ce2efe4e499052d55bafe9a6d711",
      "metadataTypeId": 3
    },
    {
      "type": "struct RedeemedEvent",
      "concreteTypeId": "412848be2f37b1c798d1dc354fd6a2ca3684ab985a70e1af44071c6d1aa224d5",
      "metadataTypeId": 4
    },
    {
      "type": "struct RefundedEvent",
      "concreteTypeId": "8d1f3c59db6ef0b871331fbe30909bfe1e1b8d0cd0171df5aca1cd6652b098bf",
      "metadataTypeId": 5
    },
    {
      "type": "struct std::address::Address",
      "concreteTypeId": "f597b637c3b0f588fb8d7086c6f4735caa3122b85f0423b82e489f9bb58e2308",
      "metadataTypeId": 6
    },
    {
      "type": "struct std::asset_id::AssetId",
      "concreteTypeId": "c0710b6731b1dd59799cf6bef33eee3b3b04a2e40e80a0724090215bbf2ca974",
      "metadataTypeId": 7
    },
    {
      "type": "struct std::bytes::Bytes",
      "concreteTypeId": "cdd87b7d12fe505416570c294c884bca819364863efe3bf539245fa18515fbbb",
      "metadataTypeId": 8
    },
    {
      "type": "u256",
      "concreteTypeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
    }
  ],
  "metadataTypes": [
    {
      "type": "enum UnsafeParams",
      "metadataTypeId": 0,
      "components": [
        {
          "name": "ZeroAddressRedeemer",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "ZeroTimelock",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "ZeroAmount",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        }
      ]
    },
    {
      "type": "enum UnsafeTransfer",
      "metadataTypeId": 1,
      "components": [
        {
          "name": "InvalidAsset",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "InvalidAmount",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        }
      ]
    },
    {
      "type": "raw untyped ptr",
      "metadataTypeId": 2
    },
    {
      "type": "struct InitiatedEvent",
      "metadataTypeId": 3,
      "components": [
        {
          "name": "order_ID",
          "typeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        },
        {
          "name": "secret_hash",
          "typeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        },
        {
          "name": "amount",
          "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        }
      ]
    },
    {
      "type": "struct RedeemedEvent",
      "metadataTypeId": 4,
      "components": [
        {
          "name": "order_ID",
          "typeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        },
        {
          "name": "secret_hash",
          "typeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        },
        {
          "name": "secret",
          "typeId": 8
        }
      ]
    },
    {
      "type": "struct RefundedEvent",
      "metadataTypeId": 5,
      "components": [
        {
          "name": "order_ID",
          "typeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        }
      ]
    },
    {
      "type": "struct std::address::Address",
      "metadataTypeId": 6,
      "components": [
        {
          "name": "bits",
          "typeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        }
      ]
    },
    {
      "type": "struct std::asset_id::AssetId",
      "metadataTypeId": 7,
      "components": [
        {
          "name": "bits",
          "typeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        }
      ]
    },
    {
      "type": "struct std::bytes::Bytes",
      "metadataTypeId": 8,
      "components": [
        {
          "name": "buf",
          "typeId": 9
        },
        {
          "name": "len",
          "typeId": 10
        }
      ]
    },
    {
      "type": "struct std::bytes::RawBytes",
      "metadataTypeId": 9,
      "components": [
        {
          "name": "ptr",
          "typeId": 2
        },
        {
          "name": "cap",
          "typeId": 10
        }
      ]
    },
    {
      "type": "u64",
      "metadataTypeId": 10
    }
  ],
  "functions": [
    {
      "inputs": [
        {
          "name": "redeemer",
          "concreteTypeId": "f597b637c3b0f588fb8d7086c6f4735caa3122b85f0423b82e489f9bb58e2308"
        },
        {
          "name": "timelock",
          "concreteTypeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        },
        {
          "name": "amount",
          "concreteTypeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        },
        {
          "name": "secret_hash",
          "concreteTypeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        }
      ],
      "name": "initiate",
      "output": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903",
      "attributes": [
        {
          "name": "payable",
          "arguments": []
        },
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "initiator",
          "concreteTypeId": "f597b637c3b0f588fb8d7086c6f4735caa3122b85f0423b82e489f9bb58e2308"
        },
        {
          "name": "redeemer",
          "concreteTypeId": "f597b637c3b0f588fb8d7086c6f4735caa3122b85f0423b82e489f9bb58e2308"
        },
        {
          "name": "timelock",
          "concreteTypeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        },
        {
          "name": "amount",
          "concreteTypeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        },
        {
          "name": "secret_hash",
          "concreteTypeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        }
      ],
      "name": "initiate_on_behalf",
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "payable",
          "arguments": []
        },
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "redeemer",
          "concreteTypeId": "f597b637c3b0f588fb8d7086c6f4735caa3122b85f0423b82e489f9bb58e2308"
        },
        {
          "name": "timelock",
          "concreteTypeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        },
        {
          "name": "amount",
          "concreteTypeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        },
        {
          "name": "secret_hash",
          "concreteTypeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        },
        {
          "name": "signature",
          "concreteTypeId": "cdd87b7d12fe505416570c294c884bca819364863efe3bf539245fa18515fbbb"
        }
      ],
      "name": "initiate_with_signature",
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "payable",
          "arguments": []
        },
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "order_ID",
          "concreteTypeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        },
        {
          "name": "signature",
          "concreteTypeId": "cdd87b7d12fe505416570c294c884bca819364863efe3bf539245fa18515fbbb"
        }
      ],
      "name": "instant_refund",
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "order_ID",
          "concreteTypeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        }
      ],
      "name": "instant_refund_digest",
      "output": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "order_ID",
          "concreteTypeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        },
        {
          "name": "secret",
          "concreteTypeId": "cdd87b7d12fe505416570c294c884bca819364863efe3bf539245fa18515fbbb"
        }
      ],
      "name": "redeem",
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "order_ID",
          "concreteTypeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        }
      ],
      "name": "refund",
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    }
  ],
  "loggedTypes": [
    {
      "logId": "10098701174489624218",
      "concreteTypeId": "8c25cb3686462e9a86d2883c5688a22fe738b0bbc85f458d2d2b5f3f667c6d5a"
    },
    {
      "logId": "7642187645296980519",
      "concreteTypeId": "6a0e812c60ce32272fec27674115bfb9f4ad3a91d73b6fbb5e0ae33b60a13a22"
    },
    {
      "logId": "13213829929622723620",
      "concreteTypeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
    },
    {
      "logId": "17696813611398264200",
      "concreteTypeId": "f597b637c3b0f588fb8d7086c6f4735caa3122b85f0423b82e489f9bb58e2308"
    },
    {
      "logId": "1970142151624111756",
      "concreteTypeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
    },
    {
      "logId": "13866877265493744985",
      "concreteTypeId": "c0710b6731b1dd59799cf6bef33eee3b3b04a2e40e80a0724090215bbf2ca974"
    },
    {
      "logId": "17429166926954047258",
      "concreteTypeId": "f1e0d6f9f415271a3b3f021e940e5c3b24ba3c3bab4a7d7e35ff36362823392d"
    },
    {
      "logId": "10177942823591106054",
      "concreteTypeId": "8d3f5112b0625606638ebdeb0911afb338b7ce2efe4e499052d55bafe9a6d711"
    },
    {
      "logId": "10168912840257106104",
      "concreteTypeId": "8d1f3c59db6ef0b871331fbe30909bfe1e1b8d0cd0171df5aca1cd6652b098bf"
    },
    {
      "logId": "4695082593206907335",
      "concreteTypeId": "412848be2f37b1c798d1dc354fd6a2ca3684ab985a70e1af44071c6d1aa224d5"
    }
  ],
  "messagesTypes": [],
  "configurables": [
    {
      "name": "token",
      "concreteTypeId": "c0710b6731b1dd59799cf6bef33eee3b3b04a2e40e80a0724090215bbf2ca974",
      "offset": 39248
    }
  ]
};

const storageSlots: StorageSlot[] = [
  {
    "key": "1f9ed0b8268df2e54d7d07807e0d2cce1db0eb5332a17bb3ef69c75583f9a264",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "e996da44c383ee4c0a363938896d69039876f9919c2e8070a9e2a7234f26e4f7",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  }
];

export class HTLCFuelInterface extends Interface {
  constructor() {
    super(abi);
  }

  declare functions: {
    initiate: FunctionFragment;
    initiate_on_behalf: FunctionFragment;
    initiate_with_signature: FunctionFragment;
    instant_refund: FunctionFragment;
    instant_refund_digest: FunctionFragment;
    redeem: FunctionFragment;
    refund: FunctionFragment;
  };
}

export class HTLCFuel extends Contract {
  static readonly abi = abi;
  static readonly storageSlots = storageSlots;

  declare interface: HTLCFuelInterface;
  declare functions: {
    initiate: InvokeFunction<[redeemer: AddressInput, timelock: BigNumberish, amount: BigNumberish, secret_hash: string], boolean>;
    initiate_on_behalf: InvokeFunction<[initiator: AddressInput, redeemer: AddressInput, timelock: BigNumberish, amount: BigNumberish, secret_hash: string], void>;
    initiate_with_signature: InvokeFunction<[redeemer: AddressInput, timelock: BigNumberish, amount: BigNumberish, secret_hash: string, signature: Bytes], void>;
    instant_refund: InvokeFunction<[order_ID: string, signature: Bytes], void>;
    instant_refund_digest: InvokeFunction<[order_ID: string], string>;
    redeem: InvokeFunction<[order_ID: string, secret: Bytes], void>;
    refund: InvokeFunction<[order_ID: string], void>;
  };

  constructor(
    id: string | Address,
    accountOrProvider: Account | Provider,
  ) {
    super(id, abi, accountOrProvider);
  }
}
